### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by e2e0** [typedanimetools/kodik-video-links#8]
If I use the video link from the example, everything works correctly. When I use any of the api link, for example "http://kodik.info/serial/20576/191e6ff83fb13152bf08c291c3d90f8e/720p", I get the error "TypeError: Cannot convert undefined or null to object". Does the functionality not work for all links?

**Comment by neverlane** [comment]
@e2e0 братанн проверю позже че там и пофикшу, и попробуй проверить в npm.im/kodikwrapper класс VideoLinks

**Comment by neverlane** [comment]
крч проверил, ты скорее всего ссылку на сезон указал (а для сириков надо серию именно)
метод `/video-links` получает ссылку на серию/фильм
